export const TECHNOLOGIES = [
    {id: 543, name: 'HTML'},
    {id: 12, name: 'CSS'},
    {id: 5173, name: 'React.js'},
    {id: 45, name: 'C'},
    {id: 565, name: 'Pyton'},
    {id: 746, name: 'JavaScript'},
    {id: 8080, name: 'Flask'},
    {id: 124, name: 'C++'},
    {id: 155, name: 'GoLang'},
    {id: 5000, name: 'Express.js'},
    {id: 541, name: 'Git'},
    {id: 1111, name: 'SQL'},
    {id: 3000, name: 'FastAPI'},
    {id: 101, name: 'MySQL'},
]